name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ main ]
permissions:
  packages: write
  contents: read
jobs:
  # Build the dockerfile
  Docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/nsunny-ram/demo-nextjs:latest
